name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - main

# Add permissions block
permissions:
  contents: write
  pages: write
  id-token: write # Required for OIDC token generation

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build
          touch _site/.nojekyll

      - name: Configure Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true # Enable GitHub Pages if not already enabled

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
